# -*- coding: utf-8 -*-
"""spark_xgboost_pmml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYXG63m8W99iA9IwRvu9sLK4-05FToh4

# Testing Spark Pipeline to PMML

Objective: To test pipeline (data processing + spark xgboost) and convert to PMML.

### Packages/Libraries Installation
"""

!java --version

# Install OpenJDK 11
!apt-get install -y openjdk-11-jdk-headless -qq > /dev/null

# Configure Java 11 as the default version
!update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java

# Set JAVA_HOME environment variable for PySpark
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"

# Verify the Java version
!java --version

!python --version

!pip install pyspark==3.5.0
!pip uninstall -y dataproc-spark-connect # can comment this out, if the pyspark version required is correctly installed

import os
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
from pyspark.ml.feature import (
    StringIndexer,
    OneHotEncoder,
    Imputer,
    VectorAssembler,
)
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.tuning import ParamGridBuilder, CrossValidator
from pyspark.ml import Pipeline
from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.ml.wrapper import JavaEstimator, JavaModel
from pyspark.ml.util import JavaMLWritable, JavaMLReadable

# only need these to create test samples
from pyspark.sql.types import StructType, StructField, DoubleType, StringType, IntegerType

"""### Environment Setup

Configure the Spark environment by setting the PYSPARK_SUBMIT_ARGS environment variable to include the required JPMML and XGBoost libraries.

"""

# must run in fresh kernel, before creating spark session
packages = ",".join([
    "org.jpmml:pmml-sparkml:3.1.9",         #generic PMML exporter for Spark ML
    "org.jpmml:pmml-sparkml-xgboost:3.1.9", #bridges Spark XGBoost models → PMML
    "ml.dmlc:xgboost4j-spark_2.12:3.1.1",   #implement/train xgb
])

os.environ["PYSPARK_SUBMIT_ARGS"] = f'--packages {packages} pyspark-shell'

spark = (SparkSession.builder
         .appName("XGBoostPMML")
         .getOrCreate())

print("Spark:", spark.version)
print("SparkSession initialized with XGBoost and PMML packages.")

"""### Create Python Wrapper for Scala-based XGB

Python wrapper that allows PySpark to use the Scala-based XGBoost classifier by forwarding parameters from Python to the underlying Java/Scala implementation
"""

# Wrapper for the XGBoost Model
class XGBoostClassificationModel(JavaModel):
    pass

# Wrapper for the XGBoost Classifier Estimator
class XGBoostClassifier(JavaEstimator, JavaMLWritable, JavaMLReadable):
    def __init__(self, **kwargs):
        super(XGBoostClassifier, self).__init__()
        # Instantiate the Scala XGBoostClassifier object
        self._java_obj = self._new_java_obj("ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier")

        # Iterate through kwargs and call the corresponding setters on the Java object
        for param, value in kwargs.items():
            # Construct the setter name (e.g., 'objective' -> 'setObjective')
            setter_name = "set" + param[0].upper() + param[1:]
            if hasattr(self._java_obj, setter_name):
                getattr(self._java_obj, setter_name)(value)
            else:
                print(f"Warning: Setter {setter_name} not found on Java object.")

    def _create_model(self, java_model):
        # Return the Python wrapper for the created Java model
        return XGBoostClassificationModel(java_model)

j = spark._jvm.ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier()
params = j.params()

for p in params:
    print(p.name(), "->", p.doc())

"""### Create Samples Dataset"""

data = [
    (1.2, "cat_a", 5.6, 0),
    (4.5, "cat_b", 8.9, 1),
    (2.1, "cat_a", None, 0), # Missing f3
    (5.4, "cat_b", 9.8, 1),
    (1.0, "cat_a", 3.0, 0),
    (None, "cat_b", 6.0, 1), # Missing f1
    (2.2, "cat_a", 4.4, 0),
    (5.5, "cat_b", 7.7, 1)
]

# Define schema to ensure correct types (especially for None values)
schema = StructType([
    StructField("f1", DoubleType(), True),
    StructField("f2", StringType(), True), # Categorical
    StructField("f3", DoubleType(), True),
    StructField("label", IntegerType(), True)
])
df = spark.createDataFrame(data, schema)

"""### Pipeline (preprocessing + assembler + xgb)"""

imputer = Imputer(inputCols=["f1", "f3"], outputCols=["f1_imp", "f3_imp"], strategy="mean")
indexer = StringIndexer(inputCol="f2", outputCol="f2_idx", handleInvalid="keep")
encoder = OneHotEncoder(inputCols=["f2_idx"], outputCols=["f2_ohe"])

# Assembling into a single vector
assembler = VectorAssembler(inputCols=["f1_imp", "f2_ohe", "f3_imp"], outputCol="features")

# XGB Classifier
xgb = XGBoostClassifier(labelCol="label", featuresCol="features", objective="binary:logistic", numWorkers=1, nthread=1)

pipeline = Pipeline(stages=[imputer, indexer, encoder, assembler, xgb])
print("Pipeline with Imputation and OHE created.")
df.show(5)

print("Fitting pipeline...")
pipeline_model = pipeline.fit(df)
preds = pipeline_model.transform(df)

print("\nPredictions:")
preds.select("f1", "f2", "f3", "prediction", "probability").show(5, truncate=False)

"""### Convert XGB to PMML"""

# Access the JVM gateway directly (alternative to installing pyspark2pmml) and convert Python objects to Java objects
java_pipeline_model = pipeline_model._to_java()
java_schema = df._jdf.schema()

# Define PMMLBuilder from the loaded JARs
PMMLBuilder = spark.sparkContext._jvm.org.jpmml.sparkml.PMMLBuilder

# Instantiate the builder with the schema and model
pmml_builder = PMMLBuilder(java_schema, java_pipeline_model)
print("PMMLBuilder instantiated successfully via JVM.")

JavaFile = spark.sparkContext._jvm.java.io.File
target_file = JavaFile("xgboost_model.pmml")

# Export the model using the pmml_builder instance
pmml_builder.buildFile(target_file)

if os.path.exists("xgboost_model.pmml"):
    print("PMML file exported successfully to xgboost_model.pmml")
else:
    print("Failed to export PMML file.")

"""### Test the Model, not the PMML"""

test_data = [
    (3.2, "cat_a", 6.7),
    (4.5, "cat_c", 7.0),
    (4.5, "cat_a", None),
]
test_df = spark.createDataFrame(test_data, ["f1", "f2", "f3"])

# Use the trained pipeline model for inference
predictions = pipeline_model.transform(test_df)
print("Inference Results:")
predictions.select("f1", "f2", "f3", "prediction").show()

"""### Load and Test PMML Model"""

!pip install pypmml_spark pypmml

import os
import pandas as pd
from pyspark.sql import SparkSession

# stop current spark
try:
    spark.stop()
except NameError:
    pass

if "PYSPARK_SUBMIT_ARGS" in os.environ:
    del os.environ["PYSPARK_SUBMIT_ARGS"]

# init Spark with the pmml4s-spark package
spark = SparkSession.builder \
    .appName("PMMLScoring") \
    .config("spark.jars.packages", "org.pmml4s:pmml4s-spark_2.12:1.0.0") \
    .getOrCreate()

# using same test data
test_data = [
    (3.2, "cat_a", 6.7),
    (4.5, "cat_c", 7.0),
    (4.5, "cat_a", None),
]
test_df = spark.createDataFrame(test_data, ["f1", "f2", "f3"])
print("Spark Configured Packages:", spark.sparkContext.getConf().get("spark.jars.packages"))

try:
    # TODO: Need to fix this to test using pypmml-spark/Java based
    from pypmml_spark import ScoreModel
    model = ScoreModel.fromFile('xgboost_model.pmml')
    score_df = model.transform(test_df)
    print("Successfully using pypmml-spark.")


except Exception as e:
    print(f"\nWarning: pypmml-spark failed ({e}). Falling back to pypmml (Python-based)...")
    from pypmml import Model
    model = Model.load('xgboost_model.pmml')
    test_pd = test_df.toPandas()
    predictions = model.predict(test_pd)
    result_pd = pd.concat([test_pd, predictions], axis=1)
    score_df = spark.createDataFrame(result_pd)
    print("Successfully using pypmml used (via Pandas conversion).")

print("PMML Inference Results (Spark DataFrame):")
score_df.select("f1", "f2", "f3", "prediction").show()

